### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by mirkomilova10** [agubelu/discord-music-bot#1]
I've installed the module with npm but i have a problem. it starts up and logs in but it crashes immediately after i request a song with this error 
```
[root@vps1 ~]# node DJ.js
[19:13:52] kobim -> request xu3Bg4Klwp4
[19:13:56] NP: "[Progressive House] - Puppet - Soft Spoken [Monstercat EP Release]" (by kobim)
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn help ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
```
im running ubuntu 12 with node js 0.12.9

**Comment by halipso** [comment]
Hey how did you fix that?
