### ISSUE TITLE
Bot won't join voice channel.

### ISSUE THREAD

**Issue by jlogan640** [agubelu/discord-music-bot#18]
The bot will not join the voice channel. This time I'm 100% sure there is no typos and that the bot has permissions to access the channel. Here is an error code I am receiving when running "node bot.js" in windows powershell:
Connected!
Error: FFMPEG not found
    at Function.selectFfmpegCommand (C:\Users\jloga\Desktop\wumbobot\node_modules\prism-media\src\transcoders\ffmpeg\Ffmpeg.js:46:13)
    at new FfmpegTranscoder (C:\Users\jloga\Desktop\wumbobot\node_modules\prism-media\src\transcoders\ffmpeg\Ffmpeg.js:7:37)
    at new MediaTranscoder (C:\Users\jloga\Desktop\wumbobot\node_modules\prism-media\src\transcoders\MediaTranscoder.js:10:19)
    at new Prism (C:\Users\jloga\Desktop\wumbobot\node_modules\prism-media\src\Prism.js:5:23)
    at VoiceConnection (C:\Users\jloga\Desktop\wumbobot\node_modules\discord.js\src\client\voice\VoiceConnection.js:45:18)
    at Promise (C:\Users\jloga\Desktop\wumbobot\node_modules\discord.js\src\client\voice\ClientVoiceManager.js:63:22)
    at ClientVoiceManager.joinChannel (C:\Users\jloga\Desktop\wumbobot\node_modules\discord.js\src\client\voice\ClientVoiceManager.js:45:12)
    at VoiceChannel.join (C:\Users\jloga\Desktop\wumbobot\node_modules\discord.js\src\structures\VoiceChannel.js:117:30)
    at Client.bot.on (C:\Users\jloga\Desktop\wumbobot\node_modules\discord-music-bot\musicbot.js:523:17)
    at emitNone (events.js:91:20)

I have FFMPEG installed in the same folder as bot.js

**Comment by jlogan640** [comment]
I also have every single file listed above present in all the locations indicated by the error message.

**Comment by jlogan640** [comment]
Also here is what powershell shows when I enter a song via "!search !search rnKbImRPhTE:"
(Knockin' on Heaven's Door - Bob Dylan)

TypeError: Cannot read property 'playStream' of null
    at play_next_song (C:\Users\jloga\Desktop\wumbobot\node_modules\discord-music-bot\musicbot.js:414:34)
    at ytdl.getInfo (C:\Users\jloga\Desktop\wumbobot\node_modules\discord-music-bot\musicbot.js:390:5)
    at C:\Users\jloga\Desktop\wumbobot\node_modules\discord-music-bot\node_modules\ytdl-core\lib\info.js:194:11
    at Object.exports.parallel (C:\Users\jloga\Desktop\wumbobot\node_modules\discord-music-bot\node_modules\ytdl-core\lib\util.js:321:5)
    at C:\Users\jloga\Desktop\wumbobot\node_modules\discord-music-bot\node_modules\ytdl-core\lib\info.js:176:14
    at C:\Users\jloga\Desktop\wumbobot\node_modules\discord-music-bot\node_modules\ytdl-core\lib\sig.js:61:7
    at IncomingMessage.<anonymous> (C:\Users\jloga\Desktop\wumbobot\node_modules\discord-music-bot\node_modules\ytdl-core\lib\request.js:43:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
PS C:\Users\jloga\Desktop\wumbobot>

I don't know what to do anymore I've been tinkering with it all night so now i'll just wait for an answer lol. I hope I gave enough info.
