### ISSUE TITLE
Bot isn't running

### ISSUE THREAD

**Issue by RandomPerson435** [agubelu/discord-music-bot#33]
After setting it up, I attempted to start the bot multiple times and got the same error message : 
throw err;
    ^

Error: Cannot find module 'discord-music-bot'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/bot.js:1:73)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3

I even tried installing the bot with the -g flag (npm install -g discord-music-bot) and got the same result as last time. Are there any fixes to this?

Any help is appreciated, thanks!

**Comment by RandomPerson435** [comment]
I decided to use a bot with python since there was no response.
