### ISSUE TITLE
npm install discord-music-bot not working

### ISSUE THREAD

**Issue by dzoavits4342** [agubelu/discord-music-bot#6]
when I type npm install discord-music-bot into my console it starts downloading but after it downloads and when I try to run the bot its saying Error: Cannot find module 'discord-music-bot'

**Comment by agubelu** [comment]
Try installing it globally adding the -g flag:

`npm install -g discord-music-bot`

**Comment by CodeOrangeZ** [comment]
I am receiving this error: /Users/node_modules/discord.js/src/client/voice/pcm/FfmpegConverterEngine.js:80
  throw new Error(
  ^

Error: FFMPEG was not found on your system, so audio cannot be played. Please make sure FFMPEG is installed and in your PATH.

how do you fix this?

**Comment by Note2Self** [comment]
@CodeOrangeZ You're missing FFmpeg and it's function convert and stream video/audio, You can either do `npm install ffmpeg
` or download a compiled version of FFmpeg (ffmpeg.exe)

**Comment by ayoubmadrid** [comment]
@CodeOrangeZ try `npm i -S ffmpeg-binaries` and maby it will also tell you that you need opus-engine if it does try to install opus-script by `npm install -S opusscript`

**Comment by LemunDesigns** [comment]
@Note2Self @ayoubmadrid @CodeOrangeZ 
For me "npm i -s ffmpeg-binaries" taking for ever to load and never loads. What should i do?

**Comment by AnriGameS** [comment]
Help me plz

`C:\Users\Usuario\Desktop\MusicBot>npm install discord-music-bot

> ref@1.3.5 install C:\Users\Usuario\node_modules\ref
> node-gyp rebuild


C:\Users\Usuario\node_modules\ref>if not defined npm_config_node_gyp (node "D:\NodeJS\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (D:\NodeJS\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at D:\NodeJS\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at D:\NodeJS\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "D:\\NodeJS\\node.exe" "D:\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Usuario\node_modules\ref
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

> node-opus@0.2.7 install C:\Users\Usuario\node_modules\node-opus
> node-gyp rebuild


C:\Users\Usuario\node_modules\node-opus>if not defined npm_config_node_gyp (node "D:\NodeJS\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (D:\NodeJS\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at D:\NodeJS\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at D:\NodeJS\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "D:\\NodeJS\\node.exe" "D:\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Usuario\node_modules\node-opus
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN discord.js@11.2.1 requires a peer of bufferutil@^3.0.2 but none was installed.
npm WARN discord.js@11.2.1 requires a peer of erlpack@hammerandchisel/erlpack but none was installed.
npm WARN discord.js@11.2.1 requires a peer of opusscript@^0.0.3 but none was installed.
npm WARN discord.js@11.2.1 requires a peer of sodium@^2.0.1 but none was installed.
npm WARN discord.js@11.2.1 requires a peer of libsodium-wrappers@^0.5.4 but none was installed.
npm WARN discord.js@11.2.1 requires a peer of uws@^0.14.5 but none was installed.
npm WARN Usuario@1.0.0 No description
npm WARN Usuario@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 (node_modules\ref):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "D:\\NodeJS\\node.exe" "D:\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install" "discord-music-bot"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-opus@0.2.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-opus@0.2.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-opus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-opus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-opus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Usuario\Desktop\MusicBot\npm-debug.log`
