### ISSUE TITLE
Crashes when requesting a song

### ISSUE THREAD

**Issue by Bluethefurry** [agubelu/discord-music-bot#8]
as soon as i request a song it crashes:

> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn help ENOENT
>     at exports._errnoException (util.js:1012:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
>     at onErrorNT (internal/child_process.js:348:16)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
>

**Comment by Bluethefurry** [comment]
Fixed, npm opus was missing
